# Generated by Django 3.0.2 on 2020-02-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('our_blog', models.CharField(choices=[('Instant', 'Instant'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', '\tMonthly')], max_length=9)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
