# Generated by Django 3.0.2 on 2020-02-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
    ]
