# Generated by Django 3.0.2 on 2020-02-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_user_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(default='surat', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
    ]
