# Generated by Django 3.0.2 on 2020-02-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_describe', models.TextField(null=True)),
                ('category_image', models.ImageField(null=True, upload_to='category-images/')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=30)),
                ('product_desc', models.TextField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product-images/')),
                ('product_type', models.CharField(max_length=60)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorys', to='dealer.Category')),
            ],
        ),
    ]
