# Generated by Django 3.0.2 on 2020-02-10 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='creaed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='add_products',
            name='product_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Post_advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_advertise', to='dealer.Category')),
                ('mobile_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_advertise', to=settings.AUTH_USER_MODEL)),
                ('product_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usr', to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_advertise', to='dealer.Add_Products')),
            ],
        ),
    ]
